### Importing Libararies

In [135]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

### Reading Data

In [136]:
df_train = pd.read_csv("train_genetic_disorders.csv")
df_test = pd.read_csv("test_genetic_disorders.csv")

In [137]:
df_train.shape

(22083, 45)

In [138]:
df_test.shape

(9463, 43)

In [139]:
missing_col = set(df_train.columns) - set(df_test.columns)
missing_col

{'Disorder Subclass', 'Genetic Disorder'}

In [140]:
df_train.head()

,Patient Id,Patient Age,Genes in mother's side,Inherited from father,Maternal gene,Paternal gene,Blood cell count (mcL),Patient First Name,Family Name,Father's name,...,Birth defects,White Blood cell count (thousand per microliter),Blood test result,Symptom 1,Symptom 2,Symptom 3,Symptom 4,Symptom 5,Genetic Disorder,Disorder Subclass
0,PID0x6418,2.0,Yes,No,Yes,No,4.760603,Richard,NaN,Larre,...,NaN,9.857562,NaN,1.0,1.0,1.0,1.0,1.0,Mitochondrial genetic inheritance disorders,Leber's hereditary optic neuropathy
1,PID0x25d5,4.0,Yes,Yes,No,No,4.910669,Mike,NaN,Brycen,...,Multiple,5.522560,normal,1.0,NaN,1.0,1.0,0.0,NaN,Cystic fibrosis
2,PID0x4a82,6.0,Yes,No,No,No,4.893297,Kimberly,NaN,Nashon,...,Singular,NaN,normal,0.0,1.0,1.0,1.0,1.0,Multifactorial genetic inheritance disorders,Diabetes
3,PID0x4ac8,12.0,Yes,No,Yes,No,4.705280,Jeffery,Hoelscher,Aayaan,...,Singular,7.919321,inconclusive,0.0,0.0,1.0,0.0,0.0,Mitochondrial genetic inheritance disorders,Leigh syndrome
4,PID0x1bf7,11.0,Yes,No,NaN,Yes,4.720703,Johanna,Stutzman,Suave,...,Multiple,4.098210,NaN,0.0,0.0,0.0,0.0,NaN,Multifactorial genetic inheritance disorders,Cancer

In [141]:
df_train.tail()

,Patient Id,Patient Age,Genes in mother's side,Inherited from father,Maternal gene,Paternal gene,Blood cell count (mcL),Patient First Name,Family Name,Father's name,...,Birth defects,White Blood cell count (thousand per microliter),Blood test result,Symptom 1,Symptom 2,Symptom 3,Symptom 4,Symptom 5,Genetic Disorder,Disorder Subclass
22078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22079,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22080,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22081,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22082,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [142]:
df_train.describe()

,Patient Age,Blood cell count (mcL),Mother's age,Father's age,Test 1,Test 2,Test 3,Test 4,Test 5,No. of previous abortion,White Blood cell count (thousand per microliter),Symptom 1,Symptom 2,Symptom 3,Symptom 4,Symptom 5
count,19643.000000,21011.000000,15293.000000,15322.000000,18992.0,18958.0,18970.0,18962.0,18939.0,18957.000000,18965.000000,18955.000000,18899.000000,19008.000000,18987.000000,18956.000000
mean,6.974851,4.899004,34.522527,41.942436,0.0,0.0,0.0,1.0,0.0,2.000106,7.484680,0.592034,0.552886,0.537405,0.497393,0.460804
std,4.322584,0.199829,9.847256,13.027701,0.0,0.0,0.0,0.0,0.0,1.411488,2.653633,0.491470,0.497208,0.498612,0.500006,0.498474
min,0.000000,4.092727,18.000000,20.000000,0.0,0.0,0.0,1.0,0.0,0.000000,3.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.000000,4.763230,26.000000,31.000000,0.0,0.0,0.0,1.0,0.0,1.000000,5.419026,0.000000,0.000000,0.000000,0.000000,0.000000
50%,7.000000,4.899548,35.000000,42.000000,0.0,0.0,0.0,1.0,0.0,2.000000,7.473071,1.000000,1.000000,1.000000,0.000000,0.000000
75%,11.000000,5.033977,43.000000,53.000000,0.0,0.0,0.0,1.0,0.0,3.000000,9.528684,1.000000,1.000000,1.000000,1.000000,1.000000
max,14.000000,5.609829,51.000000,64.000000,0.0,0.0,0.0,1.0,0.0,4.000000,12.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [143]:
df_train.describe(include="object")

,Patient Id,Genes in mother's side,Inherited from father,Maternal gene,Paternal gene,Patient First Name,Family Name,Father's name,Institute Name,Location of Institute,...,Folic acid details (peri-conceptional),H/O serious maternal illness,H/O radiation exposure (x-ray),H/O substance abuse,Assisted conception IVF/ART,History of anomalies in previous pregnancies,Birth defects,Blood test result,Genetic Disorder,Disorder Subclass
count,21011,21011,20724,18317,21011,21011,11771,21011,16151,21011,...,18998,18959,18964,18921,19007,18945,18959,18977,18962,18943
unique,21011,2,2,2,2,2480,6051,15777,27,26,...,2,2,4,4,2,2,2,4,3,9
top,PID0x6418,Yes,No,Yes,No,James,Smith,Sager,Not applicable,-,...,Yes,No,Not applicable,-,Yes,Yes,Singular,slightly abnormal,Mitochondrial genetic inheritance disorders,Leigh syndrome
freq,1,12509,12508,10125,11887,394,151,6,8011,10386,...,9625,9500,4807,4797,9555,9605,9509,4855,9686,4893

# Data Cleaning

In [167]:
df_train.duplicated().sum()

0

In [145]:
df_train.isnull().sum().sort_values(ascending=False).head(10)

Family Name                                   10312
Mother's age                                   6790
Father's age                                   6761
Institute Name                                 5932
Autopsy shows birth defect (if applicable)     5236
Maternal gene                                  3766
Symptom 2                                      3184
H/O substance abuse                            3162
Test 5                                         3144
Follow-up                                      3142
dtype: int64

In [146]:
df_test.isnull().sum().sort_values(ascending=False).head(10)

Family Name                                   9316
Maternal gene                                 3829
Heart Rate (rates/min                         3014
Respiratory Rate (breaths/min)                3013
Institute Name                                2170
Autopsy shows birth defect (if applicable)    1345
Inherited from father                          717
Symptom 1                                      173
Place of birth                                 173
Folic acid details (peri-conceptional)         173
dtype: int64

In [147]:
#checking null rows in training data
df_train[df_train.isnull().all(1)].shape[0]

1072

In [148]:
#checking null rows in testing data
df_test[df_test.isnull().all(1)].shape[0]

173

In [149]:
df_train = df_train[df_train.isnull().all(1)!=True]
df_test = df_test[df_test.isnull().all(1)!=True]

In [150]:
df_train.shape

(21011, 45)

In [151]:
df_test.shape

(9290, 43)

### Dropping unwanted attributes

In [152]:
col_to_drop = ["Patient Id","Patient First Name","Family Name","Father's name","Institute Name","Location of Institute","Test 1","Test 2","Test 3","Test 4","Test 5","Parental consent","Mother's age","Father's age"]

In [153]:
df_train = df_train.drop(columns=col_to_drop)
df_test = df_test.drop(columns=col_to_drop)

In [154]:
df_train.shape

(21011, 31)

In [155]:
df_test.shape

(9290, 29)

### Renaming columns

In [156]:
new_columns = {
    "Genes in mother's side": "maternal_gene_defect",
    "Inherited from father": "paternal_gene_defect",
    "Maternal gene": "maternal_gene",
    "Paternal gene": "paternal_gene",
    "Respiratory Rate (breaths/min)": "respiratory_rate",
    "Heart Rate (rates/min)": "heart_rate",
    "Parental consent": "parental_consent",
    "Follow-up": "follow_up",
    "Birth asphyxia": "birth_asphyxia",
    "Autopsy shows birth defect (if applicable)": "birth_defect_autopsy",
    "Place of birth": "birth_place",
    "Folic acid details (peri-conceptional)": "folic_acid_supplement",
    "H/O serious maternal illness": "maternal_illness_history",
    "H/O radiation exposure (x-ray)": "radiation_exposure_history",
    "H/O substance abuse": "substance_abuse_history",
    "Assisted conception IVF/ART": "assisted_conception",
    "History of anomalies in previous pregnancies": "previous_pregnancy_anomalies",
    "Birth defects": "birth_defects",
    "Blood test result": "blood_test_result",
    "Genetic Disorder": "genetic_disorder",
    "Disorder Subclass": "disorder_subclass",
    "Patient Age": "patient_age",
    "Blood cell count (mcL)": "RBC_count",
    "No. of previous abortion": "previous_abortions",
    "White Blood cell count (thousand per microliter)": "white_blood_cell_count"
}

In [157]:
df_train = df_train.rename(columns = new_columns)
df_test = df_test.rename(columns = new_columns)

In [158]:
df_train.head()

,patient_age,maternal_gene_defect,paternal_gene_defect,maternal_gene,paternal_gene,RBC_count,Status,respiratory_rate,Heart Rate (rates/min,follow_up,...,birth_defects,white_blood_cell_count,blood_test_result,Symptom 1,Symptom 2,Symptom 3,Symptom 4,Symptom 5,genetic_disorder,disorder_subclass
0,2.0,Yes,No,Yes,No,4.760603,Alive,Normal (30-60),Normal,High,...,NaN,9.857562,NaN,1.0,1.0,1.0,1.0,1.0,Mitochondrial genetic inheritance disorders,Leber's hereditary optic neuropathy
1,4.0,Yes,Yes,No,No,4.910669,Deceased,Tachypnea,Normal,High,...,Multiple,5.522560,normal,1.0,NaN,1.0,1.0,0.0,NaN,Cystic fibrosis
2,6.0,Yes,No,No,No,4.893297,Alive,Normal (30-60),Tachycardia,Low,...,Singular,NaN,normal,0.0,1.0,1.0,1.0,1.0,Multifactorial genetic inheritance disorders,Diabetes
3,12.0,Yes,No,Yes,No,4.705280,Deceased,Tachypnea,Normal,High,...,Singular,7.919321,inconclusive,0.0,0.0,1.0,0.0,0.0,Mitochondrial genetic inheritance disorders,Leigh syndrome
4,11.0,Yes,No,NaN,Yes,4.720703,Alive,Tachypnea,Tachycardia,Low,...,Multiple,4.098210,NaN,0.0,0.0,0.0,0.0,NaN,Multifactorial genetic inheritance disorders,Cancer

### Remove rows without target variables

In [159]:
df_train = df_train[df_train['disorder_subclass'].isnull()!=True]

In [160]:
disorder_mapping = {
        "Leber's hereditary optic neuropathy": "Mitochondrial genetic inheritance disorders",
        "Leigh syndrome": "Mitochondrial genetic inheritance disorders",
        "Mitochondrial myopathy": "Mitochondrial genetic inheritance disorders",
        "Alzheimer's": "Multifactorial genetic inheritance disorders",
        "Cancer": "Multifactorial genetic inheritance disorders",
        "Diabetes": "Multifactorial genetic inheritance disorders",
        "Cystic fibrosis": "Single-gene inheritance diseases",
        "Hemochromatosis": "Single-gene inheritance diseases",
        "Tay-Sachs": "Single-gene inheritance diseases",
    }

In [161]:
def fill_missing_genetic_disorder(row):
    if pd.isnull(row["Genetic Disorder"]) and row["Disorder Subclass"] in disorder_mapping:
        return disorder_mapping[row["Disorder Subclass"]]
    return row["Genetic Disorder"]

df["Genetic Disorder"] = df.apply(infer_genetic_disorder, axis=1)

In [162]:
df_train.shape

(18943, 31)

In [163]:
df_train.isnull().sum().sort_values(ascending=False).head(10)

birth_defect_autopsy       3760
maternal_gene              2309
Symptom 2                  1827
substance_abuse_history    1802
Symptom 5                  1797
white_blood_cell_count     1786
genetic_disorder           1783
respiratory_rate           1781
Gender                     1767
Symptom 1                  1764
dtype: int64